config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"

  # foods
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes do
    resources :recipe_foods
    get 'general_shopping_list', to: 'general_shopping#index'
  end

  get 'public_recipes', to: 'recipes#public_index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  validates :name, presence: { message: 'Please enter a name' }, length: { minimum: 2 }
  validates :description, length: { maximum: 1000, message: 'The description is too long' }

  def total_price
    recipe_foods.map(&:total_price).sum
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user: current_user)
  end

  def public_index
    @recipes = Recipe.where(public: true).includes(:recipe_foods).order(created_at: :desc)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      flash[:success] = 'Recipe saved successfully'
      redirect_to recipes_path
    else
      flash[:error] = "Invalid input, recipe didn't get saved"
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(user_params)
      render json: { public: @recipe.public }
    else
      render @recipe.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find_by(user: current_user, id: params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def user_params
    params.require(:recipe).permit(:public)
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description,
                                   :public).merge(user: current_user)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<%= stylesheet_link_tag 'recipes/index', media: 'all' %>
<div class="recipe__container">
  <div class="recipe__add">
    <%= link_to 'Add Recipe', new_recipe_path %>
  </div>
  <% if @recipes.empty? %>
    <div class="recipe">
      <div class="recipe__title">
        <h2>No recipes found. Consider adding one</h2>
      </div>
    </div>
  <% end %>
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <div class="recipe__title">
        <h2><%= recipe.name %></h2>
        <%= link_to "Delete", recipe_path(recipe.id), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            }
        %>
      </div>
      <p class="recipe__description"><%= recipe.description %></p>
      <a href=<%= recipe_path(recipe.id) %> class="recipe__info">
        <%= image_tag "info_icon.png", height: 50, id: 'info__img' %>
      </a>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<%= stylesheet_link_tag 'recipes/new', media: 'all' %>
<div class="recipe__add">
  <h2 class="recipe__title">Add new Recipe</h2>
  <%= form_with model: @recipe, url: recipes_path , local: true do |f| %>

  <div class="recipe__container">
    <div class="recipe__form">
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
    </div>

    <div class="recipe__form">
      <%= f.label :preparation_time %> <br>
      <%= f.text_field :preparation_time %>
    </div>

    <div class="recipe__form">
      <%= f.label :cooking_time %> <br>
      <%= f.text_field :cooking_time %>
    </div>

    <div class="recipe__form">
      <%= f.label :public %> <br>
      <%= f.check_box :public, {}, "true", "false" %>
    </div>

    <div class="recipe__form">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <%= f.submit class:'recipe__submit' %> <br>
  </div>

  <% end %>
</div>

app/views/recipes/public_index.html.erb
<%= stylesheet_link_tag 'recipes/index', media: 'all' %>
<div class="recipe__container">
  <% if @recipes.empty? %>
    <div class="recipe">
      <div class="recipe__title">
        <h2>No recipes found.</h2>
      </div>
    </div>
  <% end %>
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <div class="recipe__title">
        <h2><%= recipe.name %></h2>
        <span style="font-style: italic; font-size: medium">By: <%= recipe.user.name %></span>
      </div>
      <div class="recipe__description">
        <p>Total food items: <%= recipe.recipe_foods.length %></p>
        <p>Total price: $<%= recipe.total_price %></p>
      </div>
      <a href=<%= recipe_path(recipe.id) %> class="recipe__info">
        <%= image_tag "info_icon.png", height: 50 %>
      </a>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= stylesheet_link_tag 'recipes/show', media: 'all' %>
<div class="recipe__info">
  <h2 class="recipe__title"><%= @recipe.name %></h2>
  <div class="recipe__vision">
    <p>Preparation time: <%= @recipe.preparation_time %></p>
    <% if current_user == @recipe.user %>
    <p>
      Public
      <label class="recipe__switch">
        <input type="checkbox" id="recipe_public" <%= @recipe.public ? 'checked' : '' %>>
        <span class="slider"></span>
      </label>
    </p>
    <% end %>
  </div>
  <p>Cooking time: <%= @recipe.cooking_time %></p>
  <p><%= @recipe.description %></p>
  <div class="recipe__action">
    <%= link_to 'Generate Shopping list' , recipe_general_shopping_list_path(@recipe.id), class:"recipe__button" %>
    <% if current_user == @recipe.user %>
      <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe.id), class:"recipe__button" %>
    <% end %>
  </div>
</div>

<div class="recipe__detail">
  <table>
    <% if @recipe_foods.empty? %>
      <h2>No Recipe Food found, click on add ingredient to add one</h2>
    <% end %>
    <thead>
      <tr>
        <td>Food</td>
        <td>Quantity</td>
        <td>Value ( per unit) </td>
        <% if current_user == @recipe.user %>
          <td>Actions</td>
        <% end %>
      </tr>
    </thead>
    <tbody>
    <% @recipe_foods.each do |recipe_food|%>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %><%= recipe_food.food.measurement_unit %></td>
        <td><%= recipe_food.food.price %></td>
        <% if current_user == @recipe.user %>
        <td>
          <%= link_to "remove", recipe_recipe_food_path(recipe_food.recipe.id, recipe_food.id), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              }, class:"recipe__remove"
          %>
        </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const checkbox = document.getElementById('recipe_public');
    checkbox.addEventListener('click', function() {
      const url = "<%= recipe_path %>";
      const csrfToken = document.querySelector('meta[name="csrf-token"]').content;
      const active = checkbox.checked;
      fetch(url, {
        method: 'PATCH',
        headers: {
          'X-CSRF-Token': csrfToken,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ recipe: { public: active } })
      })
      .then(response => response.json())
      .then(data => {
        // Update the checkbox with the new value from the server
        checkbox.checked = !checkbox.checked;
      })
      .catch(error => console.log(error));
    });
  });
</script>