config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"

  # foods
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes do
    resources :recipe_foods
    get 'general_shopping_list', to: 'general_shopping#index'
  end

  get 'public_recipes', to: 'recipes#public_index'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true, length: { minimum: 3 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where(user: current_user) || []
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<div class="card">
  <div class="card-header">
    <%= link_to "Add Food", new_food_path, class: "btn btn-primary"%>
  </div>
  <div class="card-body">
    <table id="example" class="table table-striped datatable" style="width:100%">
      <thead>
      <tr>
        <th>Food</th>
        <th>Measurement unit</th>
        <th>Unit price</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <td><%= food.quantity %></td>
          <td>
            <%= link_to "Delete", food_path(food), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure you want to delete this food?"
            } %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="d-flex flex-column justify-content-center h-100 m-5">
  <%= form_for @food, url: foods_path(@food) do |f| %>

    <h1 class="card-header text-center">Add Food</h1>
    <div class="card-body">
      <div class="form-group py-3">
        <%= f.label :name, class: "form-label" %><br/>
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
      </div>

      <div class="form-group py-3">
        <%= f.label :measurement_unit, class: "form-label" %><br/>
        <%= f.text_field :measurement_unit, autocomplete: "measurement_unit", class: "form-control" %>
      </div>

      <div class="form-group py-3">
        <%= f.label :price, class: "form-label" %>
        <%= f.number_field :price, autocomplete: "price", class: "form-control" %>
      </div>

      <div class="form-group py-3">
        <%= f.label :quantity, class: "form-label" %><br />
        <%= f.number_field :quantity, autocomplete: "quantity", class: "form-control" %>
      </div>
    </div>

    <div class="card-footer">
      <%= f.submit "Add", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>