config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"

  # foods
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes do
    resources :recipe_foods
    get 'general_shopping_list', to: 'general_shopping#index'
  end

  get 'public_recipes', to: 'recipes#public_index'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def total_price
    food.price * quantity
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @food = Food.find_by(name: recipe_food_params['name'],
                         measurement_unit: recipe_food_params['measurement_unit'], user: current_user)

    # If food doesn't exist
    if @food.nil?
      # Create Food first with 0 quantity
      @food = Food.new(recipe_food_params)
      @food.user = current_user
      @food.quantity = 0
      if @food.save
        @recipe_food = RecipeFood.new(quantity: recipe_food_params['quantity'],
                                      food: @food, recipe: @recipe)
        save_recipe_food(@recipe_food)
      else
        flash[:error] = "Invalid input, Food didn't get saved"
        render :new
      end
    else
      @recipe_food = RecipeFood.new(quantity: recipe_food_params['quantity'],
                                    food: @food, recipe: @recipe)
      save_recipe_food(@recipe_food)
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:name, :measurement_unit, :price, :quantity)
  end

  def save_recipe_food(recipe_food)
    if recipe_food.save
      flash[:success] = 'Recipe food saved successfully'
      redirect_to recipe_path(params[:recipe_id])
    else
      flash[:error] = "Invalid input, recipe didn't get saved"
      render :new
    end
  end
end

app/views/recipe_foods/new.html.erb
<%= stylesheet_link_tag 'recipe_foods/new', media: 'all' %>
<div class="recipe-food__add">
  <h2 class="recipe-food__title">Add new ingredient</h2>
  <%= form_with model: @recipe_food, url: recipe_recipe_foods_path(params[:recipe_id]) , local: true do |f| %>

  <div class="recipe-food__container">
    <div class="recipe-food__form">
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
    </div>

    <div class="recipe-food__form">
      <%= f.label :measurement_unit %> <br>
      <%= f.text_field :measurement_unit %>
    </div>

    <div class="recipe-food__form">
      <%= f.label :price %> <br>
      <%= f.text_field :price %>
    </div>

    <div class="recipe-food__form">
      <%= f.label :quantity %> <br>
      <%= f.text_field :quantity %>
    </div>

    <%= f.submit class: 'recipe-food__submit'%> <br>
  </div>

  <% end %>
</div>